import Design from "@/screens/Design/Design";

export const NAVIGATION = {
  home: 'Home',
  login: 'Login',
  profile: 'Profile',
  count :'Count',
  add :'Add',
  Spread : 'Spread',
  Mod : 'Mod',
  Show : 'Show',
  Design : 'Design',
  Des : 'Des',
  Datepicker : 'Datepicker',
  Asyne : 'Asyne',
  Storage : 'Storage',
  Asyobj : 'Asyobj',
  Asyobjv : 'Asyobjv',
  Image : 'Image',
  Clockt : 'Clockt',
  Clockpratice : 'Clockpratice',
  Firstrd : 'Firstrd',
  Second : 'Second',
  reduxapi : 'reduxapi',
  Reduxnavigation : 'Reduxnavigation',
  Reduxhome : 'Reduxhome',
  Calculator : 'Calculator',
  Newcal : 'Newcal',
  QrCode : 'QrCode',
  scanQr : 'scanQr',
  genrateQr : 'genrateQr',
  todo : 'todo',
  todolist : 'todolist',
  arraymethod : 'arraymethod',
  ScreenA : 'ScreenA',
  ScreenB : 'ScreenB',
  ScreenC : 'ScreenC',
  LinkingScreen : 'LinkingScreen',
  calenderPickerApp : 'calenderPickerApp',
};
